#Google Cloud Automatic App Engine deploy
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['source', 'repos', 'clone', 'config', '--project', 'highlow']
- name: 'python:latest'
  args: ['bash', '/workspace/config/build.sh']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project', 'highlow']
