name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v1
      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.1
        with:
          # The service account key which will be used for authentication.
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Clone config repo
        run: gcloud source repos clone config --project highlow
      - name: Run build script
        run: ./config/build.sh false
      - name: Run deployment
        run: gcloud app deploy
        env:
          CLOUDSDK_CORE_PROJECT: highlow
