name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v1
      - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@master
        with: 
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
      - name: Clone config repo
        run: gcloud source repos clone config --project highlow
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
         python-version: 3.7
      - name: Run build script
        run: ./config/build.sh false
      - name: Run deployment
        run: gcloud app deploy
        env:
          CLOUDSDK_CORE_PROJECT: highlow
      - name: Delete artifacts bucket
        run: gsutil rm -r gs://us.artifacts.highlow.appspot.com
